### ISSUE TITLE
race condition with multiple numpys in a single shell

### ISSUE THREAD

**Issue by jhgoebbert** [Xpra-org/xpra-html5#160]
I came across the following error while loading xpra:
```
2022-03-08 20:00:47,065  cannot load enc_nvjpeg (nvjpeg encoder)
Traceback (most recent call last):
  File "/p/software/juwels/stages/2022/software/xpra/4.3.2-GCCcore-11.2.0/lib/python3.9/site-packages/xpra/codecs/loader.py", line 52, in codec_import_check
    ic =  __import__(class_module, {}, {}, classnames)
  File "xpra/codecs/nvjpeg/encoder.pyx", line 8, in init xpra.codecs.nvjpeg.encoder
  File "/p/software/juwels/stages/2022/software/SciPy-bundle/2021.10-gcccoremkl-11.2.0-2021.4.0/lib/python3.9/site-packages/numpy/__init__.py", line 150, in <module>
    from . import core
  File "/p/software/juwels/stages/2022/software/SciPy-bundle/2021.10-gcccoremkl-11.2.0-2021.4.0/lib/python3.9/site-packages/numpy/core/__init__.py", line 51, in <module>
    del os.environ[envkey]
  File "/p/software/juwels/stages/2022/software/Python/3.9.6-GCCcore-11.2.0/lib/python3.9/os.py", line 695, in __delitem__
    raise KeyError(key) from None
KeyError: 'OPENBLAS_MAIN_FREE'
```
After digging through the code I come to the following conclusion:  
In `numpy/core/__init__.py` the environment variable 'OPENBLAS_MAIN_FREE' is set in [line 19](https://github.com/numpy/numpy/blob/v1.22.3/numpy/core/__init__.py#L19) if not existant and removed (if set in line 19) in [line 52](https://github.com/numpy/numpy/blob/v1.22.3/numpy/core/__init__.py#L52).
To my understanding, this can result in a race condition if two numpys are initialized at the same time (by two threads) in the same shell.
It might be an answer to the error shown above.

**Comment by totaam** [comment]
This could be solved in xpra by wrapping all numpy imports with an indirection layer, but that's not an elegant solution.

Shouldn't this issue be solved by numpy itself? (builds without openblas don't have this issue)
