### ISSUE TITLE
Error moving jupyterlab-desktop window

### ISSUE THREAD

**Issue by iDmple** [Xpra-org/xpra-html5#244]
I'm not able to move jupyterlab-desktop window on commit 8c36971731e82050b49f11e41329c7a7552615e0 and https://github.com/Xpra-org/xpra/commit/0fa092904f581f9d9b95a5c1797891a6e2c95669.

There is this error in the dev console when I try:
```
Window.js:1 Uncaught TypeError: this.div.trigger is not a function
    at XpraWindow.initiate_moveresize (Window.js:1:19513)
    at XpraClient._process_initiate_moveresize (Client.js:2:18371)
    at XpraClient._route_packet (Client.js:1:13269)
    at XpraProtocolWorkerHost.packet_handler (Client.js:1:11878)
    at Worker.<anonymous> (Protocol.js:1:455)
```

See the video example below:

https://user-images.githubusercontent.com/5065505/235166919-ba141064-20f3-4eff-85fc-3f4584bfee74.mov

I downloaded the .deb version 3.6.2-1 of Jupyterlab-desktop from [here](https://github.com/jupyterlab/jupyterlab-desktop), running on Ubuntu 20.04.

Thanks for your help. Let me know if you need any other infos.

**Comment by totaam** [comment]
@iDmple does the (untested) commit above help?

**Comment by iDmple** [comment]
@totaam This fixed the problem! Thanks a bunch!
